apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todo
type: Opaque
stringData:
  db-url: "postgres://postgres:postgres@postgres.todo.svc.cluster.local:5432/todos?sslmode=disable"
